make the nightly test script leave data on failure.
git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/cado-nfs/trunk@688 3eaf19af-ecc0-40f6-b43f-672aa0c71c71

diff --git a/nightly-test b/nightly-test
--- a/nightly-test
+++ b/nightly-test
@@ -67,4 +67,11 @@ date
 CADO_COLOR=0 ./factor.sh 71641520761751435455133616475667090434063332228247871795429 -t 4 -ssh expected_factorization=200429218120815554269743635437,357440504101388365610785389017
 CADO_COLOR=0 ./factor.sh 90377629292003121684002147101760858109247336549001090677693 -t 2 expected_factorization=260938498861057,588120598053661,760926063870977,773951836515617
 
-/bin/rm -fr "$DIR"
+if [ "$rc" = 0 ] ; then
+    echo OK
+    if ! [ "$CADO_DEBUG" ] ; then
+        /bin/rm -fr "$DIR"
+    fi
+else
+    echo "FAILED ; data left in $DIR"
+fi
